/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import static java.lang.Integer.parseInt;

import controllers.LendingController;
import models.Lending;
import util.tableModels.PendingLendingsTableModel;
import util.Settings;
import util.cellRenderers.TimeColumnCellRenderer;
import views.viewUser.ViewUsersDialog;
import views.viewBook.ViewBooksDialog;

/**
 *
 * @author Femen
 */
public class MainScreen extends javax.swing.JFrame {

    PendingLendingsTableModel lendingsModel;
    LendingController controller;
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        lendingsModel = new PendingLendingsTableModel();
        LendingsTable.setModel(lendingsModel);
        controller = new LendingController();
        loadLendings();
        decorateLendingsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        LendingsHeaderPanel = new javax.swing.JPanel();
        LendingsTitle = new javax.swing.JLabel();
        NewLendingButton = new javax.swing.JButton();
        ReturnLendingButton = new javax.swing.JButton();
        LendingsPanel = new javax.swing.JPanel();
        LendingsScroll = new javax.swing.JScrollPane();
        LendingsTable = new javax.swing.JTable();
        ButtonsPanel = new javax.swing.JPanel();
        ViewUsers = new javax.swing.JButton();
        ViewBooks = new javax.swing.JButton();
        RegisterBook = new javax.swing.JButton();
        RegisterUser = new javax.swing.JButton();
        lendingTimeField = new javax.swing.JFormattedTextField();
        lendingTimeLabel = new javax.swing.JLabel();
        setLendingTimeButton = new javax.swing.JButton();
        fineLabel = new javax.swing.JLabel();
        fineField = new javax.swing.JFormattedTextField();
        setFineButton = new javax.swing.JButton();
        maxBorrowedLabel = new javax.swing.JLabel();
        maxBorrowedField = new javax.swing.JFormattedTextField();
        setMaxBorrowedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 660));
        setPreferredSize(new java.awt.Dimension(680, 660));

        MainPanel.setBackground(new java.awt.Color(204, 184, 165));
        MainPanel.setMinimumSize(new java.awt.Dimension(632, 614));

        TitlePanel.setBackground(new java.awt.Color(120, 100, 82));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Library Manager");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        LendingsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LendingsTitle.setForeground(new java.awt.Color(120, 100, 82));
        LendingsTitle.setText("Current lendings");

        NewLendingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewLendingButton.setText("Lend a book");
        NewLendingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewLendingButtonMouseClicked(evt);
            }
        });
        NewLendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLendingButtonActionPerformed(evt);
            }
        });

        ReturnLendingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReturnLendingButton.setText("Return a book");
        ReturnLendingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnLendingButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LendingsHeaderPanelLayout = new javax.swing.GroupLayout(LendingsHeaderPanel);
        LendingsHeaderPanel.setLayout(LendingsHeaderPanelLayout);
        LendingsHeaderPanelLayout.setHorizontalGroup(
            LendingsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LendingsHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LendingsTitle)
                .addGap(18, 18, 18)
                .addComponent(NewLendingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnLendingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LendingsHeaderPanelLayout.setVerticalGroup(
            LendingsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LendingsHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LendingsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReturnLendingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addGroup(LendingsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NewLendingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LendingsTitle)))
                .addContainerGap())
        );

        LendingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User name", "Book title", "Lending date", "Time (days)", "Return"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LendingsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LendingsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LendingsTableMouseClicked(evt);
            }
        });
        LendingsScroll.setViewportView(LendingsTable);

        javax.swing.GroupLayout LendingsPanelLayout = new javax.swing.GroupLayout(LendingsPanel);
        LendingsPanel.setLayout(LendingsPanelLayout);
        LendingsPanelLayout.setHorizontalGroup(
            LendingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LendingsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        LendingsPanelLayout.setVerticalGroup(
            LendingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LendingsScroll)
        );

        ViewUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewUsers.setText("View users");
        ViewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewUsersMouseClicked(evt);
            }
        });

        ViewBooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewBooks.setText("View books");
        ViewBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewBooksMouseClicked(evt);
            }
        });
        ViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBooksActionPerformed(evt);
            }
        });

        RegisterBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterBook.setText("Register book");
        RegisterBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBookMouseClicked(evt);
            }
        });
        RegisterBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBookActionPerformed(evt);
            }
        });

        RegisterUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterUser.setText("Register user");
        RegisterUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterUserMouseClicked(evt);
            }
        });

        lendingTimeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        lendingTimeField.setText("7");

        lendingTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lendingTimeLabel.setText("Lending time (days):");

        setLendingTimeButton.setText("set");
        setLendingTimeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLendingTimeButtonMouseClicked(evt);
            }
        });

        fineLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fineLabel.setText("Fine for day of delay:");

        fineField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        fineField.setText("0,25");

        setFineButton.setText("set");
        setFineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setFineButtonMouseClicked(evt);
            }
        });

        maxBorrowedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maxBorrowedLabel.setText("Max. borrowed books:");

        maxBorrowedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        maxBorrowedField.setText("3");

        setMaxBorrowedButton.setText("set");
        setMaxBorrowedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setMaxBorrowedButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(ViewUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fineLabel)
                            .addComponent(lendingTimeLabel)
                            .addComponent(maxBorrowedLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(maxBorrowedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setMaxBorrowedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(fineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setFineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(lendingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setLendingTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(lendingTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lendingTimeField)
                    .addComponent(setLendingTimeButton))
                .addGap(35, 35, 35)
                .addComponent(fineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fineField)
                    .addComponent(setFineButton))
                .addGap(40, 40, 40)
                .addComponent(maxBorrowedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBorrowedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setMaxBorrowedButton))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LendingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LendingsHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(LendingsHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LendingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewLendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewLendingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewLendingButtonActionPerformed

    private void ViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBooksActionPerformed

    private void RegisterBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBookActionPerformed

    private void RegisterBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBookMouseClicked
        RegisterBookDialog registerBookDialog = new RegisterBookDialog(this, rootPaneCheckingEnabled);
        registerBookDialog.setVisible(true);
    }//GEN-LAST:event_RegisterBookMouseClicked

    private void RegisterUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterUserMouseClicked
        RegisterUserDialog registerUserDialog = new RegisterUserDialog(this, rootPaneCheckingEnabled);
        registerUserDialog.setVisible(true);
    }//GEN-LAST:event_RegisterUserMouseClicked

    private void ViewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewUsersMouseClicked
        ViewUsersDialog viewUsersDialog = new ViewUsersDialog(this, rootPaneCheckingEnabled);
        viewUsersDialog.setVisible(true);
    }//GEN-LAST:event_ViewUsersMouseClicked

    private void NewLendingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewLendingButtonMouseClicked
        NewLendingDialog newLendingDialog = new NewLendingDialog(this, rootPaneCheckingEnabled);
        
        newLendingDialog.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosed(WindowEvent e) {
               loadLendings();
               LendingsTable.updateUI();
           } 
        });
        
        newLendingDialog.setVisible(true);
    }//GEN-LAST:event_NewLendingButtonMouseClicked

    private void ReturnLendingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnLendingButtonMouseClicked
        ReturnBookDialog returnBookDialog = new ReturnBookDialog(this, rootPaneCheckingEnabled);
        
        returnBookDialog.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosed(WindowEvent e) {
               loadLendings();
               LendingsTable.updateUI();
           } 
        });
        
        returnBookDialog.setVisible(true);
    }//GEN-LAST:event_ReturnLendingButtonMouseClicked

    private void ViewBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBooksMouseClicked
        ViewBooksDialog viewBooksDialog = new ViewBooksDialog(this, rootPaneCheckingEnabled);
        viewBooksDialog.setVisible(true);
    }//GEN-LAST:event_ViewBooksMouseClicked

    private void setLendingTimeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLendingTimeButtonMouseClicked
        Settings.setLendingTime(parseInt(lendingTimeField.getText()));
        decorateLendingsTable();
    }//GEN-LAST:event_setLendingTimeButtonMouseClicked

    private void setFineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setFineButtonMouseClicked
        Settings.setFine(Float.parseFloat(fineField.getText().replace(",", ".")));
    }//GEN-LAST:event_setFineButtonMouseClicked

    private void setMaxBorrowedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMaxBorrowedButtonMouseClicked
        Settings.setMaxLendings(parseInt(maxBorrowedField.getText()));
    }//GEN-LAST:event_setMaxBorrowedButtonMouseClicked

    private void LendingsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LendingsTableMouseClicked
        int rowIndex = LendingsTable.rowAtPoint(evt.getPoint());
        int columnIndex = LendingsTable.columnAtPoint(evt.getPoint());
        
        if(columnIndex == 4) {
            Lending lending = lendingsModel.getLendingByIndex(rowIndex); // Get the clicked lending
            
            ReturnBookDialog returnBookDialog = new ReturnBookDialog(this, rootPaneCheckingEnabled); // Open ReturnBookDialog
            returnBookDialog.addWindowListener(new WindowAdapter() {
               @Override
               public void windowClosed(WindowEvent e) {
                   loadLendings();
                   LendingsTable.updateUI();
               } 
            });
            
            returnBookDialog.setLending(lending); // Call method to automatically set the fields in ReturnBookDialog

            returnBookDialog.setVisible(true);
        }
        
    }//GEN-LAST:event_LendingsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JPanel LendingsHeaderPanel;
    private javax.swing.JPanel LendingsPanel;
    private javax.swing.JScrollPane LendingsScroll;
    private javax.swing.JTable LendingsTable;
    private javax.swing.JLabel LendingsTitle;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton NewLendingButton;
    private javax.swing.JButton RegisterBook;
    private javax.swing.JButton RegisterUser;
    private javax.swing.JButton ReturnLendingButton;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton ViewBooks;
    private javax.swing.JButton ViewUsers;
    private javax.swing.JFormattedTextField fineField;
    private javax.swing.JLabel fineLabel;
    private javax.swing.JFormattedTextField lendingTimeField;
    private javax.swing.JLabel lendingTimeLabel;
    private javax.swing.JFormattedTextField maxBorrowedField;
    private javax.swing.JLabel maxBorrowedLabel;
    private javax.swing.JButton setFineButton;
    private javax.swing.JButton setLendingTimeButton;
    private javax.swing.JButton setMaxBorrowedButton;
    // End of variables declaration//GEN-END:variables

    public void decorateLendingsTable() {
        LendingsTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        LendingsTable.getTableHeader().setBackground(new Color(120,100,82));
        LendingsTable.getTableHeader().setForeground(new Color(255,255,255));
        LendingsTable.setAutoCreateRowSorter(true);
        LendingsTable.getColumnModel().getColumn(3).setCellRenderer(new TimeColumnCellRenderer());
    }
    
    public void loadLendings() {
        List<Lending> lendings = controller.getAllPending();
        lendingsModel.setLendings(lendings);
    }
    
}
